### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Wwarrior1** [Wwarrior1/Useful-scripts#1]
- [x] Atom - https://flight-manual.atom.io/getting-started/sections/installing-atom/#debian-and-ubuntu-debapt
- [x] CURL - `apt install curl`
- [x] max_user_watches (https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers#the-technical-details)
- [x] Backports to some apps (e.g. Gimp)
- [x] Stacer (https://oguzhaninan.github.io/Stacer-Web/)
- [x] Metamorphose 2 (http://www.webupd8.org/2017/01/metamorphose-2-bulk-rename-tool.html)
- [x] PDFsam (info - can be fetched from KDE Store)
- [x] JDownloader (http://www.webupd8.org/2012/04/install-jdownloader-2-pre-beta-in.html)
- [ ] LibreOffice (add-apt-repository ppa:libreoffice/ppa)
